# Reference: https://github.com/marketplace/actions/setup-node-js-environment 

name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Show NodeJS version    
      run: npm --version

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts

    # - name: Install Truffle
    #   run: npm install truffle@5.4.29 -g # cannot use truffle@latest due to https://github.com/sc-forks/solidity-coverage/issues/696
    
    # - name: Install Dependencies
    #   run: npm install      
    
    - name: Run tests
      run: npm run test:all
